version: '3'

services:
  frontend:
    build: ./frontend
    container_name: task-frontend
    restart: always
    ports:
      - 3000:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: task-backend
    restart: always
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    depends_on:
      - database

  database:
    container_name: task-database
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
